#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Comparación entre método original y nuevo de carga de datos TET

Este script compara la lógica de carga del script original
(old_scripts/Armado de Dataframe para clusterizar.py) con la
implementación actual (scripts/tet/data_loader.py)
"""

import sys
import os

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

print("=" * 80)
print("COMPARACIÓN: MÉTODO ORIGINAL vs NUEVO DE CARGA TET")
print("=" * 80)
print()

print("MÉTODO ORIGINAL (old_scripts/Armado de Dataframe para clusterizar.py)")
print("-" * 80)
print()
print("Características:")
print("  1. Lee archivos .mat del directorio 'resampled'")
print("  2. Usa tabla de dosis hardcodeada con índices: s01-s20 (sin s14)")
print("  3. Separa datos en 4 listas según condición:")
print("     - alta: DMT con dosis alta")
print("     - baja: DMT con dosis baja")
print("     - rs_alta: Reposo asociado a sesión DMT alta")
print("     - rs_baja: Reposo asociado a sesión DMT baja")
print("  4. Concatena solo DMT (alta + baja) sin incluir reposo")
print("  5. Resultado: CSV con ~10,800 filas (300 bins × 18 sujetos × 2 dosis)")
print("     - Primeras 5,400 filas: dosis alta")
print("     - Siguientes 5,400 filas: dosis baja")
print("  6. NO incluye columnas de metadata (subject, session_id, state, dose)")
print("  7. Solo incluye las 15 dimensiones fenomenológicas")
print()

print("MÉTODO NUEVO (scripts/tet/data_loader.py)")
print("-" * 80)
print()
print("Características:")
print("  1. Lee archivos .mat del directorio especificado")
print("  2. Usa config.DOSIS con índices: S01-S20 (sin S14)")
print("  3. Carga TODOS los archivos (DMT + RS) en un solo DataFrame")
print("  4. Agrega columnas de metadata:")
print("     - subject: ID del sujeto (S01, S02, etc.)")
print("     - session_id: Número de sesión (1 o 2)")
print("     - state: Tipo de sesión (DMT o RS)")
print("     - dose: Dosis (Alta o Baja)")
print("     - t_bin: Índice temporal (0, 1, 2, ...)")
print("     - t_sec: Tiempo en segundos (0, 30, 60, ...)")
print("  5. Resultado: DataFrame con ~22,800 filas (19 sujetos × 4 sesiones × 300 bins)")
print("  6. Incluye tanto DMT como RS")
print("  7. Formato 'long' con metadata completa")
print()

print("DIFERENCIAS CLAVE")
print("-" * 80)
print()
print("1. ALCANCE DE DATOS:")
print("   Original: Solo DMT (sin reposo)")
print("   Nuevo:    DMT + RS (todas las sesiones)")
print()
print("2. ESTRUCTURA:")
print("   Original: Solo dimensiones, sin metadata")
print("   Nuevo:    Dimensiones + metadata completa")
print()
print("3. ORGANIZACIÓN:")
print("   Original: Bloques separados por dosis (alta primero, baja después)")
print("   Nuevo:    Ordenado por archivo (sujeto/sesión)")
print()
print("4. SUJETOS:")
print("   Original: 18 sujetos (falta S12 según comentario en PIPELINE.md)")
print("   Nuevo:    19 sujetos (incluye S12 si está en el directorio)")
print()
print("5. PROPÓSITO:")
print("   Original: Específico para clustering (solo DMT, sin metadata)")
print("   Nuevo:    General (análisis completo con metadata)")
print()

print("COMPATIBILIDAD CON ANÁLISIS ORIGINAL")
print("-" * 80)
print()
print("Para replicar el análisis de clustering original desde el nuevo formato:")
print()
print("  # Filtrar solo DMT")
print("  dmt_data = data[data['state'] == 'DMT']")
print()
print("  # Separar por dosis")
print("  alta = dmt_data[dmt_data['dose'] == 'Alta']")
print("  baja = dmt_data[dmt_data['dose'] == 'Baja']")
print()
print("  # Extraer solo dimensiones (sin metadata)")
print("  dimension_cols = config.TET_DIMENSION_COLUMNS")
print("  alta_dims = alta[dimension_cols]")
print("  baja_dims = baja[dimension_cols]")
print()
print("  # Concatenar (alta primero, baja después)")
print("  clustering_data = pd.concat([alta_dims, baja_dims], ignore_index=True)")
print()

print("RECOMENDACIÓN")
print("-" * 80)
print()
print("El método NUEVO es más completo y flexible:")
print("  ✓ Incluye metadata para análisis más sofisticados")
print("  ✓ Permite filtrar por state, dose, subject según necesidad")
print("  ✓ Facilita análisis longitudinales y comparaciones RS vs DMT")
print("  ✓ Mantiene trazabilidad de cada observación")
print()
print("El método ORIGINAL es válido para:")
print("  ✓ Clustering simple de estados DMT")
print("  ✓ Comparación directa alta vs baja sin considerar sujetos")
print("  ✓ Replicar análisis legacy exactamente")
print()
print("=" * 80)
